name: Generate Snake Animation

on:
  # التشغيل التلقائي كل 24 ساعة
  schedule:
    - cron: "0 0 * * *" 
  
  # للسماح بتشغيل السكريبت يدوياً
  workflow_dispatch:
  
  # التشغيل التلقائي عند أي تحديث في المستودع
  push:
    branches:
    - master
    - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # توليد صورة الثعبان
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#4bc9b0&color_dots=#ebedf0,#111c26,#27374d,#39807e,#4bc9b0
            dist/github-contribution-grid-snake-dark.svg?color_snake=#4bc9b0&color_dots=#111c26,#1b2737,#27374d,#39807e,#4bc9b0&color_background=#0d1117
          
      # رفع الصورة الناتجة إلى فرع جديد باسم (output)
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
